Update mainpage.css
ludmilka-k/team-light-balance pull request #43
Opened 2023-02-18 20:28 UTC by StIgorek

Перевірив html у W3 валідаторі (ругався тільки що немає док-тайпу та ленг погано підключений.) Перевірив очима html/css помилку не виявив...

2023-02-18 23:59 UTC, ludmilka-k requested changes

2023-02-18 23:59 UTC, ludmilka-k commented on src/css/mainpage.css
> +*/
все це сміття треба видалити

2023-02-18 23:59 UTC, ludmilka-k commented on src/css/mainpage.css
> +/*.slide-img {
не треба залишати в гіті закоменчений код
це і так є в історії

2023-02-19 09:31 UTC, ludmilka-k approved these changes

2023-02-19 11:46 UTC, StIgorek commented
Щось я не зрозумів, моя гілка вже смержена, чи ще треба конфлікти виправити?

2023-02-19 12:00 UTC, ludmilka-k requested changes
у  тебе в пул реквести конфликт до твого ж самого коду
Потрібно репозиторий оновити Fetch  або у меню Repository Pull .Смержить main в свой бранч и разрешить конфликти. які покаже тобі Github
Тобто зробити Resolve conflicts

2023-02-19 14:03 UTC, closed without merging